package rules.devices;
dialect  "mvel"

import securityproject.model.logs.DeviceLog;
import securityproject.model.enums.LogType;
import securityproject.model.enums.AlarmSeverity;
import securityproject.service.AlarmService;
import securityproject.model.alarms.DeviceAlarm;

global AlarmService alarmService;

rule "error log"
    when
        DeviceLog(logType == LogType.ERROR, $device: deviceId, $message: message, $timestamp: timestamp, $deviceType: deviceType)
    then
        alarmService.raiseErrorAlarm($device, $message, $timestamp, AlarmSeverity.LOW, $deviceType);
end

//rule "too many requests"
//    when
//       RequestEvent($ip: address)
//       Number(intValue >= 10) from accumulate(
//           $e: RequestEvent($ip == address) over window:time(10s),
//           count($e)
//       )
//   then
//end